config/routes.rb
Rails.application.routes.draw do
  
  resources :merchants

  resources :products

  devise_for :admins, controllers: { registrations: "admins/registrations",sessions: "admins/sessions"}

  devise_for :doctors, controllers: {registrations: "doctors/registrations", sessions: "doctors/sessions" }

 

  get 'comments/create'

  resources :comunications do
    resources :comments
  end

  get 'control_users/index'

  
  devise_for :users
  
  get 'pages/prova'

  get 'pages/prezzi_mercato_agricolo'
  get 'pages/prezzi_mercato_ittico'
  get 'pages/grossisti_agricoli'
   

   root "pages#home"

end

app/models/comunication.rb
class Comunication < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

app/controllers/comunications_controller.rb
class ComunicationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comunication, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @comunications = Comunication.all
    respond_with(@comunications)
  end

  def show
    respond_with(@comunication)
  end

  def new
    @comunication = current_user.comunications.new
    respond_with(@comunication)
  end

  def edit
  end

  def create
    @comunication = current_user.comunications.new(comunication_params)
    @comunication.save
    ComunicationMailer.comunication_created(current_user,@comunication).deliver
    respond_with(:root)
  end

  def update
    @comunication.update(comunication_params)
    respond_with(@comunication)
  end

  def destroy
    @comunication.destroy
    respond_with(@comunication)
  end

  private
    def set_comunication
      #@comunication = current_user.comunications.find(params[:id])
      @comunication = Comunication.find(params[:id])
    end

    def comunication_params
      params.require(:comunication).permit(:title, :content, :user_id,:from)
    end
end

app/helpers/comunications_helper.rb
module ComunicationsHelper
end

app/views/comunications/_form.html.erb
<%= simple_form_for(@comunication,html:{class:"form-signin"}) do |f| %>
  <%= f.error_notification %>

  
    <%= f.input :title,autofocus: true,label:false,placeholder:"in cosa vuoi essere aiutato?", class:"form-control" %>
    <%= f.input :content,autofocus: true,label:false,placeholder:"Descrivici il tuo problema", class:"form-control"  %>

   

    

    <%= f.hidden_field :from, :value => current_user.email %>


   
  

  
    <%= f.button :submit,"Invia", class:"btn btn-primary" %>

<% end %>

app/views/comunications/edit.html.erb
<h1>Editing comunication</h1>

<%= render 'form' %>

<%= link_to 'Show', @comunication %> |
<%= link_to 'Back', comunications_path %>

app/views/comunications/index.html.erb
<p id="notice"> <%= notice %></p>

<% @comunications.each do |comunication| %>
<%= comunication.title %>
<%= comunication.content %>
<%= User.find(comunication.user_id).name %>
<br>

<% end %>

app/views/comunications/new.html.erb
<h1 class="text-center">Come possiamo aiutarti?</h1>

<%= render 'form' %>

<%= link_to 'Back', comunications_path %>

app/views/comunications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @comunication.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comunication.content %>
</p>

<h2> Comments </h2>
<%= render @comunication.comments %>
<br>

<%= render "comments/form" %>

<%= link_to 'Edit', edit_comunication_path(@comunication) %> |
<%= link_to 'Back', comunications_path %>