config/routes.rb
Rails.application.routes.draw do
  
  resources :merchants

  resources :products

  devise_for :admins, controllers: { registrations: "admins/registrations",sessions: "admins/sessions"}

  devise_for :doctors, controllers: {registrations: "doctors/registrations", sessions: "doctors/sessions" }

 

  get 'comments/create'

  resources :comunications do
    resources :comments
  end

  get 'control_users/index'

  
  devise_for :users
  
  get 'pages/prova'

  get 'pages/prezzi_mercato_agricolo'
  get 'pages/prezzi_mercato_ittico'
  get 'pages/grossisti_agricoli'
   

   root "pages#home"

end

app/views/pages/_homeLogged.html.erb
<% if current_user %> 

<% else %>


<p><a class="btn btn-large btn-default" href=<%= new_user_registration_path %>>Registrati</a></p>



<% end %>

app/views/pages/grossisti_agricoli.html.erb
  <% doc=exists_grossisti_agricoli_page %>
  <% title=doc.css("title").text%>
  <% @righe=doc.css(".views-table")  %>
  <% @righe.each do |intestazione| %>
  <table class="table table-condensed">
  
  <tr>    
  <th><%= intestazione.at_css("th.views-field" ".views-field-field-stand").text %></th> 
  <th><%= intestazione.at_css("th.views-field" ".views-field-title").text %></th>
  <th><%= intestazione.at_css("th.views-field" ".views-field-field-phone").text %></th>
  <th><%= intestazione.at_css("th.views-field" ".views-field-field-fax").text %></th>
  <th><%= intestazione.at_css("th.views-field" ".views-field-field-ref").text %></th>
  </tr>
  
  <% doc.css("tr", "tr.even","tr.odd").each do |riga| %>
  <% next unless stand=riga.css("td.views-field" ".views-field-field-stand")[0] %>
  <% next unless ragSociale=riga.css("td.views-field" ".views-field-title")[0] %>
  <% next unless phone=riga.css("td.views-field" ".views-field-field-phone")[0] %>
  <% next unless fax=riga.css("td.views-field" ".views-field-field-fax")[0] %>
  <% next unless ref=riga.css("td.views-field" ".views-field-field-ref")[0] %>
  
  <tr>
  <td><%= stand.content %></td>
  <td><%= ragSociale.content %></td>
  <td class="danger"><%= phone.content %></td>
  <td class="info"><%= fax.content %></td>
  <td class="warning"><%= ref.content %></td>

  </tr>
  <% end %>



  </table>

  <% end %>

app/views/pages/home.html.erb
<!-- Carousel
================================================== -->
<div id="myCarousel" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="item active">
      <img src=<%= asset_path "Agriculture.png" %> style="width:100%" class="img-responsive">
      <div class="container">
        <div class="carousel-caption">
          <h3 class="title">Il lavoro e la produzione aumenta e i guadagni si abbassano?</h3>
         
        </div>
      </div>
    </div>
    <div class="item">
      <img src=<%= asset_path "pensare5.jpg" %> class="img-responsive">
      <div class="container">
        <div class="carousel-caption">
          <h1 class="title">Pensi a come crescere una pianta sana e forte? </h1>
          
        </div>
      </div>
    </div>
    <div class="item">
      <img src=<%= asset_path "Statistiche.jpg" %> class="img-responsive">
      <div class="container">
        <div class="carousel-caption">
          <h1 class="title">Chiedi ad esperti il loro parere </h1>
          <%= render "homeLogged" %>
          
        </div>
      </div>
    </div>
  </div>
  <!-- Controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="icon-prev"></span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="icon-next"></span>
  </a>  
</div>
<!-- /.carousel -->


<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

  <!-- START THE FEATURETTES -->

  <hr class="featurette-divider">

  <div class="featurette">
    <img class="featurette-image img-circle pull-right" src=<%= asset_path "prezzi-mercato.jpg" %>>
  <a href=<%= pages_prezzi_mercato_agricolo_path %>><h2 class="featurette-heading"> <span class="text-primary">Più trasparenza nei prezzi</span></h2></a>
    <p class="lead">Vuoi essere sempre aggiornato sui prezzi dei principali <a href=<%= pages_prezzi_mercato_ittico_path %>>mercati ittici </a> e  <a href=<%= pages_prezzi_mercato_agricolo_path %>>ortofrutticoli Italiani</a>?  </p>
    <%= render "homeLogged" %>
  </div>

  <hr class="featurette-divider">

  <div class="featurette">
    <img class="featurette-image img-circle pull-left" src=<%= asset_path "patto.jpg" %>>
    <a href="<%=pages_grossisti_agricoli_path %>"><h2 class="featurette-heading"> <span class="text-warning">Cerchi un nuovo acquirente?</span></h2></a>
    <p class="lead">Stanco di lavorare molto per poi ricavare poco? <a href="<%=pages_grossisti_agricoli_path %>"> Scegli un nuovo commerciante </a></p>



    <%= render "homeLogged" %>
  </div>

  <hr class="featurette-divider">

  <div class="featurette">
    <img class="featurette-image img-circle pull-right" src=<%= asset_path "team.jpg" %>>
    <a href="<%= new_comunication_path %>"><h2 class="featurette-heading"><span class="text-muted">Fatti consigliare da esperti!!</span></h2></a>
    <p >
        Vuoi conoscere i segreti di come crescere una pianta sana, forte con buon e tanto frutto?
</p> 
    <br>
    <strong> Un team di oltre 1000 esperti, agronomi, biologi, geologi è pronto a consigliarti per ridurre al minimo il rischio di perdita e aumentare i tuoi guadagni </strong> 
    <%= render "homeLogged" %>
  </div>

  <hr class="featurette-divider">

  <!-- /END THE FEATURETTES -->


  <!-- FOOTER -->
  <footer>
    <p class="pull-right"><a href="#">Back to top</a></p>
  
  </footer>

</div><!-- /.container -->

app/views/pages/prezzi_mercato_agricolo.html.erb
  <% doc=exists_prezzi_torino_page %>
  <% title=doc.css("title").text%>
  <% @righe=doc.css(".views-table")  %>
  <% @righe.each do |intestazione| %>
  <table class="table table-condensed">
  <tr><td class="text-center"><strong style="color:red">Prezzi aggiornati il:  <%=extract_date title %></strong></td></tr>
  <tr>    
  <th><%= intestazione.at_css(".views-field-field-specie").text %></th> 
  <th><%= intestazione.at_css(".views-field-field-varieta").text %></th>
  <th><%= intestazione.at_css(".views-field-pmin").text %></th>
  <th><%= intestazione.at_css(".views-field-ppre").text %></th>
  <th><%= intestazione.at_css(".views-field-pmax").text %></th>
  <th><%= intestazione.at_css(".views-field-field-calibro").text %></th>
  <th><%= intestazione.at_css(".views-field-field-categoria").text %></th>
  <th><%= intestazione.at_css(".views-field-field-origine").text %></th>
  <th><%= intestazione.at_css(".views-field-field-unitamisura").text %></th>
  <th><%= intestazione.at_css(".views-field-field-gruppo").text %></th>
  </tr>
  <% doc.css("tr", "tr.even","tr.odd").each do |riga| %>
  <% next unless specie=riga.css("td[data-title='Specie']")[0] %>
  <% next unless varieta=riga.css("td[data-title='Varietà']")[0] %>
  <% next unless pmin=riga.css("td[data-title='P. Min']")[0] %>
  <% next unless ppre=riga.css("td[data-title='P. Pre']")[0] %>
  <% next unless pmax=riga.css("td[data-title='P. Max']")[0] %>
  <% next unless calibro=riga.css("td[data-title='Calibro']")[0] %>
  <% next unless categoria=riga.css("td[data-title='Cat.']")[0] %>
  <% next unless origine=riga.css("td[data-title='Origine']")[0] %>
  <% next unless unitamisura=riga.css("td[data-title='Unita misura']")[0] %>
  <% next unless gruppo=riga.css("td[data-title='Gruppo']")[0] %>
  <tr >
  <td><%= specie.content %></td>
  <td><%= varieta.content %></td>
  <td class="warning"><%= pmin.content %></td>
  <td class="info"><%= ppre.content %></td>
  <td class="success"><%= pmax.content %></td>
  <td><%= calibro.content %></td>
  <td><%= categoria.content %></td>
  <td><%= origine.content %></td>
  <td><%= unitamisura.content %></td>
  <td><%= gruppo.content %></td>
  </tr>
  <% end %>


  </table>

  <% end %>

app/views/pages/prezzi_mercato_ittico.html.erb
  <% doc=exists_prezzi_ismea_page %>
  <% title=doc.css("title").text%>
  <% @righe=doc.css("table.IsmeaDataTable")  %>
  <% @righe.each do |intestazione| %>
  <table class="table table-condensed">
  
  <tr>    
  <th><%= intestazione.css("th[scope='col']")[0].text %></th> 
  <th><%= intestazione.css("th[scope='col']")[1].text %></th>
  <th><%= intestazione.css("th[scope='col']")[2].text %></th>
  <th><%= intestazione.css("th[scope='col']")[3].text %></th>
  <th><%= intestazione.css("th[scope='col']")[4].text %></th>
  <th><%= intestazione.css("th[scope='col']")[5].text %></th>
  <th><%= intestazione.css("th[scope='col']")[6].text %></th>
  <th><%= intestazione.css("th[scope='col']")[7].text %></th>
    
  </tr>

  <% doc.css("tr", "tr.even","tr.odd").each do |riga| %>
  <% next unless specie=riga.css("th.odd","th.even")[0] %>
  <% next unless mercato=riga.css("td.odd","td.even")[0] %>
  <% next unless provenienza=riga.css("td.odd","td.even")[1] %>
  <% next unless pezzatura=riga.css("td.odd","td.even")[2] %>
  <% next unless prezzomin=riga.css("td.odd","td.even")[3] %>
  <% next unless prezzomax=riga.css("td.odd","td.even")[4] %>
  <% next unless prezzominprec=riga.css("td.odd","td.even")[5] %>
  <% next unless prezzomaxprec=riga.css("td.odd","td.even")[6] %>
  
  <tr>
  <td><%= specie.content %></td>
  <td><%= mercato.content %></td>
  <td><%= provenienza.content %></td>
  <td><%= pezzatura.content %></td>
  <td class="warning"><%= prezzomin.content %></td>
  <td class="info"><%= prezzomax.content %></td>
  <td class="success"><%= prezzominprec.content %></td>
  <td class="danger"><%= prezzomaxprec.content %></td>
  </tr>
  <% end %>
  

  </table>

  <% end %>

app/views/pages/prova.html.erb
<%= acquisisci_html %>