config/routes.rb
Rails.application.routes.draw do
  
  resources :merchants

  resources :products

  devise_for :admins, controllers: { registrations: "admins/registrations",sessions: "admins/sessions"}

  devise_for :doctors, controllers: {registrations: "doctors/registrations", sessions: "doctors/sessions" }

 

  get 'comments/create'

  resources :comunications do
    resources :comments
  end

  get 'control_users/index'

  
  devise_for :users
  
  get 'pages/prova'

  get 'pages/prezzi_mercato_agricolo'
  get 'pages/prezzi_mercato_ittico'
  get 'pages/grossisti_agricoli'
   

   root "pages#home"

end

app/models/merchant.rb
class Merchant < ActiveRecord::Base
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_action :set_merchant, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @merchants = Merchant.all
    respond_with(@merchants)
  end

  

  def update
   @merchant.update_attributes({:doc => Caat.exists_grossisti_agricoli_page})
   respond_with(@merchant)
  end

  def doc=(val)
  val.css("tr", "tr.even","tr.odd").each do |riga| 
       next unless specie=riga.css("td[data-title='Specie']")[0]
       next unless varieta=riga.css("td[data-title='Varietà']")[0] 
       next unless pmin=riga.css("td[data-title='P. Min']")[0] 
       next unless ppre=riga.css("td[data-title='P. Pre']")[0] 
       next unless pmax=riga.css("td[data-title='P. Max']")[0] 
       next unless calibro=riga.css("td[data-title='Calibro']")[0] 
       next unless categoria=riga.css("td[data-title='Cat.']")[0] 
       next unless origine=riga.css("td[data-title='Origine']")[0] 
       next unless unitamisura=riga.css("td[data-title='Unita misura']")[0] 
       next unless gruppo=riga.css("td[data-title='Gruppo']")[0]
      
    @merchant.assign_attributes(stand:stand.content, ragioneSociale:ragSociale.content, telefono:phone.content, fax:fax.content , referente: ref.content)
      
  end
end

  def destroy
    @merchant.destroy
    respond_with(@merchant)
  end

  private
    def set_merchant
      @merchant = Merchant.find(params[:id])
    end

    def merchant_params
      params.require(:merchant).permit(:stand, :ragioneSociale, :telefono, :fax, :referente)
    end
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/merchants/_form.html.erb
<%= simple_form_for(@merchant) do |f| %>
  <%= f.error_notification %>

  

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/merchants/edit.html.erb
<h1>Editing merchant</h1>

<%= render 'form' %>

<%= link_to 'Show', @merchant %> |
<%= link_to 'Back', merchants_path %>

app/views/merchants/index.html.erb
<h1>Lista Commercianti Agricoli</h1>

<table class="table">
  <thead>
    <tr>
      <th>Stand</th>
      <th>Ragionesociale</th>
      <th>Telefono</th>
      <th>Fax</th>
      <th>Referente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @merchants.each do |merchant| %>
      <tr>
        <td><%= merchant.stand %></td>
        <td><%= merchant.ragioneSociale %></td>
        <td class="info"><%= merchant.telefono %></td>
        <td><%= merchant.fax %></td>
        <td><%= merchant.referente %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/merchants/new.html.erb
<h1>New merchant</h1>

<%= render 'form' %>

<%= link_to 'Back', merchants_path %>

app/views/merchants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stand:</strong>
  <%= @merchant.stand %>
</p>

<p>
  <strong>Ragionesociale:</strong>
  <%= @merchant.ragioneSociale %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @merchant.telefono %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @merchant.fax %>
</p>

<p>
  <strong>Referente:</strong>
  <%= @merchant.referente %>
</p>

<%= link_to 'Edit', edit_merchant_path(@merchant) %> |
<%= link_to 'Back', merchants_path %>