config/routes.rb
Rails.application.routes.draw do
  
  resources :merchants

  resources :products

  devise_for :admins, controllers: { registrations: "admins/registrations",sessions: "admins/sessions"}

  devise_for :doctors, controllers: {registrations: "doctors/registrations", sessions: "doctors/sessions" }

 

  get 'comments/create'

  resources :comunications do
    resources :comments
  end

  get 'control_users/index'

  
  devise_for :users
  
  get 'pages/prova'

  get 'pages/prezzi_mercato_agricolo'
  get 'pages/prezzi_mercato_ittico'
  get 'pages/grossisti_agricoli'
   

   root "pages#home"

end

app/views/layouts/_header.html.erb
<nav class="navbar">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=<%= root_path %>><i class="fa fa-spinner fa-pulse"></i>PrimoS>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">

          <% if user_signed_in? %>
            <li class="dropdown">
         
          
           <li><a href=<%= products_path %>>Prezzi Mercato Agricolo</a></li>
        </li>

          
          
            <li><a href=<%= merchants_path %>>Lista Commercianti Agricoli</a></li>
                       
          
        
           <li><%= link_to "Contatta un esperto",new_comunication_path %></li>
            <li><%= link_to "Impostazioni",edit_user_registration_path %></li>
            <li><%= link_to "Log Out",destroy_user_session_path, method: :delete %></li>


          <% else %>
            
            <li><%= link_to "Login",new_user_session_path %></li>
          <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_headerAdmin.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrimoS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
<%= render "layouts/headerAdmin" %>
</header>



<div class="container">
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

******
ADMIN
******
<%= yield %>
</div>


<footer>


</footer>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrimoS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
<%= render "layouts/header" %>
</header>



<div class="container">
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

<%= yield %>

</div>


<footer>
<div class="container">

	<h7 class="text-center">Copyright © 2014-2020 Hgsystems srl, All Rights Reserved </h7>
</div>

</footer>

</body>
</html>

app/views/layouts/doctor.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrimoS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
<%= render "layouts/headerAdmin" %>
</header>



<div class="container">
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

******
DOCTOR
******

<%= yield %>
</div>


<footer>


</footer>

</body>
</html>